services:
  - type: web
    name: web-os-backend
    runtime: python
    buildCommand: "pip install -r backend/python/requirements.txt"
    startCommand: "gunicorn --chdir backend/python app:app"
    envVars:
      - key: PORT
        value: 5000
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER
        sync: false
    healthCheckPath: /login
